### ISSUE TITLE
Before performing an action, wait... 0 seconds

### ISSUE THREAD

**Issue by grand-lotus-iroh** [ZMYaro/chrome-voice-actions#11]
0 seconds?

How do we make it so there is as little lag as possible? It would make sense to me, to have a 0 second option. This would mean... what.... when I click button or press hotkey it's actively waiting for a voice command instead of waiting a 1 second?

**Comment by ZMYaro** [comment]
Implemented in https://github.com/ZMYaro/chrome-voice-actions/commit/7c4cd79b04006a423ecbabf5484f0f131bb04969.
