### ISSUE TITLE
hotkey activation

### ISSUE THREAD

**Issue by wala0003** [ZMYaro/chrome-voice-actions#3]
https://developer.chrome.com/extensions/commands

a global keyboard shortcut would be amazing. im working on using a configurable button on my tablet to launch your extension

**Comment by ZMYaro** [comment]
Added in https://github.com/ZMYaro/chrome-voice-actions/commit/04d58f87deae2c49c9a6917975444f829136b6b7.  The default shortcut key right now is `Alt+Shift+V`.

**Comment by ZMYaro** [comment]
Added keyboard shortcut info. to options page in https://github.com/ZMYaro/chrome-voice-actions/commit/67b4128c3a539f9ded47180fcafeb8c5b4265a0b.
