### ISSUE TITLE
Add “help”, “settings”, and “options” commands

### ISSUE THREAD

**Issue by skykooler** [ZMYaro/chrome-voice-actions#4]

**Comment by ZMYaro** [comment]
Thinking about this, I am a little on the fence.  Because Voice Actions for Chrome is supposed to control the browser, should it open Voice Actions options, or the Chrome help page?

**Comment by ZMYaro** [comment]
I am going to remove this from v4.6 so it does not hold up the release.  It can be added later.

**Comment by ZMYaro** [comment]
My thoughts right now are because Voice Actions for Chrome is supposed to control the browser, “help” and “settings” should open the browser help and settings pages.  On the other hand, Chrome calls browser settings “settings” and extensions options “options”, so “options” should open the Voice Actions for Chrome options page.

**Comment by ZMYaro** [comment]
To flesh this out further:

| Open Chrome Settings | Open Chrome Help | Open Voice Actions Options                |
|----------------------|------------------|-------------------------------------------|
| settings             | help             | options                                   |
| open settings        | open help        | open options                              |
| chrome settings      | chrome help      | extension options                         |
|                      |                  | voice action(s) options                   |
|                      |                  | open extension options                    |
|                      |                  | open voice action(s) options              |
|                      |                  | (open) extension/voice action(s) settings |
|                      |                  | (open) extension/voice action(s) help     |
|                      |                  | what can i say                            |

**Comment by ZMYaro** [comment]
Implemented in https://github.com/ZMYaro/chrome-voice-actions/commit/d3b13f5e12c85c4086bc7b54019b5a61afe7ed89.
